# Generated by Django 3.0.8 on 2020-12-24 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordOfMouth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20, verbose_name='サービス名')),
                ('support_quality', models.CharField(choices=[(1, '★★★★★'), (2, '★★★★'), (3, '★★★'), (4, '★★'), (5, '★')], max_length=5, verbose_name='サポートの質')),
                ('subject', models.TextField(verbose_name='サービスの感想')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='CareerDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25, verbose_name='企業名')),
                ('interview_date', models.DateField(verbose_name='面接日')),
                ('selection_stage', models.CharField(choices=[(0, 'カジュアル面談'), (1, '1次面接'), (2, '2次面接'), (3, '3次面接'), (4, '4次面接'), (5, '5次面接'), (6, '最終選考')], default=0, max_length=7, verbose_name='選考段階')),
                ('content', models.TextField(verbose_name='面接記録')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'CareerDiary',
            },
        ),
    ]
