# Generated by Django 3.0.8 on 2020-12-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_careerdiary_wordofmouth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerdiary',
            name='selection_stage',
            field=models.CharField(choices=[('CASUAL', 'カジュアル面談'), ('1', '1次面接'), ('2', '2次面接'), ('3', '3次面接'), ('4', '4次面接'), ('5', '5次面接'), ('6', '最終選考')], default=0, max_length=7, verbose_name='選考段階'),
        ),
    ]
