# Generated by Django 3.0.8 on 2020-12-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20201224_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordofmouth',
            name='support_quality',
            field=models.CharField(choices=[('5', '★★★★★'), ('4', '★★★★'), ('3', '★★★'), ('2', '★★'), ('1', '★')], max_length=5, verbose_name='サポートの質'),
        ),
    ]
