# Generated by Django 3.0.8 on 2020-12-25 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20201224_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordofmouth',
            options={'verbose_name_plural': 'WordOfMouth'},
        ),
        migrations.AddField(
            model_name='wordofmouth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-12-24 22:00', verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordofmouth',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='careerdiary',
            name='selection_stage',
            field=models.CharField(choices=[('CASUAL', 'カジュアル面談'), ('1次面接', '1次面接'), ('2次面接', '2次面接'), ('3次面接', '3次面接'), ('4次面接', '4次面接'), ('5次面接', '5次面接'), ('最終選考', '最終選考')], default=0, max_length=7, verbose_name='選考段階'),
        ),
    ]
