# Generated by Django 3.0.8 on 2020-12-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20201225_0959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordOfMouth',
        ),
    ]
