# Generated by Django 3.0.8 on 2021-01-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_delete_wordofmouth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
