# Generated by Django 3.0.8 on 2021-01-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, choices=[('1', '北海道'), ('2', '青森県'), ('3', '岩手県'), ('4', '宮城県'), ('5', '秋田県'), ('6', '山形県'), ('7', '福島県'), ('8', '茨城県'), ('9', '栃木県'), ('10', '群馬県'), ('11', '埼玉県'), ('12', '千葉県'), ('13', '東京都'), ('14', '神奈川県'), ('15', '新潟県'), ('16', '富山県'), ('17', '石川県'), ('18', '福井県'), ('19', '山梨県'), ('20', '長野県'), ('21', '岐阜県'), ('22', '静岡県'), ('23', '愛知県'), ('24', '三重県'), ('25', '滋賀県'), ('26', '京都府'), ('27', '大阪府'), ('28', '兵庫県'), ('29', '奈良県'), ('30', '和歌山県'), ('31', '鳥取県'), ('32', '島根県'), ('33', '岡山県'), ('34', '広島県'), ('35', '山口県'), ('36', '徳島県'), ('37', '香川県'), ('38', '愛媛県'), ('39', '高知県'), ('40', '福岡県'), ('41', '佐賀県'), ('42', '長崎県'), ('43', '熊本県'), ('44', '大分県'), ('45', '宮崎県'), ('46', '鹿児島県'), ('47', '沖縄県')], max_length=20, null=True, verbose_name='居住地'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthplace',
            field=models.CharField(blank=True, choices=[('1', '北海道'), ('2', '青森県'), ('3', '岩手県'), ('4', '宮城県'), ('5', '秋田県'), ('6', '山形県'), ('7', '福島県'), ('8', '茨城県'), ('9', '栃木県'), ('10', '群馬県'), ('11', '埼玉県'), ('12', '千葉県'), ('13', '東京都'), ('14', '神奈川県'), ('15', '新潟県'), ('16', '富山県'), ('17', '石川県'), ('18', '福井県'), ('19', '山梨県'), ('20', '長野県'), ('21', '岐阜県'), ('22', '静岡県'), ('23', '愛知県'), ('24', '三重県'), ('25', '滋賀県'), ('26', '京都府'), ('27', '大阪府'), ('28', '兵庫県'), ('29', '奈良県'), ('30', '和歌山県'), ('31', '鳥取県'), ('32', '島根県'), ('33', '岡山県'), ('34', '広島県'), ('35', '山口県'), ('36', '徳島県'), ('37', '香川県'), ('38', '愛媛県'), ('39', '高知県'), ('40', '福岡県'), ('41', '佐賀県'), ('42', '長崎県'), ('43', '熊本県'), ('44', '大分県'), ('45', '宮崎県'), ('46', '鹿児島県'), ('47', '沖縄県')], max_length=20, null=True, verbose_name='出身地'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='部署名 / 学部名'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('MEN', '男'), ('WOMEN', '女'), ('OTHER', 'その他')], max_length=5, null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.CharField(blank=True, choices=[('1', '情報通信業'), ('2', '金融業'), ('3', '医療・福祉'), ('4', '飲食業・宿泊業'), ('5', '建設業'), ('6', '製造業'), ('7', '電気・ガス・水道業'), ('8', '運輸・郵便業'), ('9', '不動産業'), ('10', '教育・学習支援業'), ('11', 'その他サービス業'), ('12', 'その他')], max_length=20, null=True, verbose_name='業界'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job',
            field=models.CharField(blank=True, choices=[('1', '会社員（正社員）'), ('2', '会社員（契約社員)'), ('3', '公務員'), ('4', '自営業'), ('5', '会社役員・経営者'), ('6', '自由業'), ('7', '専業主婦（夫）'), ('8', '学生'), ('9', 'パート・アルバイト'), ('10', '無職'), ('11', 'フリーランス')], max_length=20, null=True, verbose_name='お仕事'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='お名前'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ニックネーム'),
        ),
    ]
