# Generated by Django 3.0.8 on 2020-12-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='support_quality',
            field=models.CharField(choices=[('★★★★★', '★★★★★'), ('★★★★', '★★★★'), ('★★★', '★★★'), ('★★', '★★'), ('★', '★')], max_length=5, verbose_name='サポートの質'),
        ),
    ]
